tasks:
  - name: terraform
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_terraform_cli.sh
      cd $PROJECT_ROOT
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd $PROJECT_ROOT
      source ./bin/install_aws_cli.sh
      source ./bin/add_tf_alias.sh
      source ./bin/terraform_credentials.sh
      cd $PROJECT_ROOT
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform